package ru.shrprnbw.ideas.data.mapper

import ru.shrprnbw.ideas.data.remote.dto.response.NoteKeywordDto
import ru.shrprnbw.ideas.domain.entity.Keyword

fun NoteKeywordDto.toEntity(): Keyword {
    return Keyword(
        id = this.id,
        keyword = this.keyword,
        createdAt = this.createdAt,
        autoGenerated = this.autoGenerated,
        generationStatus = this.generationStatus
    )
}
