package ru.shrprnbw.ideas.data.mapper

import ru.shrprnbw.ideas.data.remote.dto.response.NoteSummaryDto
import ru.shrprnbw.ideas.domain.entity.Summary

fun NoteSummaryDto.toEntity(): Summary {
    return Summary(
        id = this.id,
        summary = this.summary,
        createdAt = this.createdAt,
        autoGenerated = this.autoGenerated,
        generationStatus = this.generationStatus
    )
}
