package ru.shrprnbw.ideas.data.mapper

import ru.shrprnbw.ideas.data.remote.dto.response.TranscriptionDto
import ru.shrprnbw.ideas.data.remote.dto.response.TranscriptionSegmentDto
import ru.shrprnbw.ideas.domain.entity.Transcription
import ru.shrprnbw.ideas.domain.entity.TranscriptionSegment

fun TranscriptionDto.toEntity(): Transcription {
    return Transcription(
        id = this.id,
        segments = this.transcription.map { it.toEntity() },
        createdAt = this.createdAt,
        autoGenerated = this.autoGenerated,
        generationStatus = this.generationStatus
    )
}

fun TranscriptionSegmentDto.toEntity(): TranscriptionSegment {
    return TranscriptionSegment(
        start = this.start,
        end = this.end,
        text = this.text,
        speaker = this.speaker
    )
}
