package ru.shrprnbw.ideas.domain.entity

data class Transcription(
    val id: String,
    val segments: List<TranscriptionSegment>,
    val createdAt: Long,
    val autoGenerated: Boolean,
    val generationStatus: String
)
