package ru.shrprnbw.ideas.data.remote.dto.response

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NoteKeywordDto(
    @SerialName("id")
    val id: Long,
    @SerialName("keyword")
    val keyword: String,
    @SerialName("createdAt")
    val createdAt: Long,
    @SerialName("autoGenerated")
    val autoGenerated: Boolean,
    @SerialName("generationStatus")
    val generationStatus: String
)
