package ru.shrprnbw.ideas.data.remote.dto.response

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NoteSummaryDto(
    @SerialName("id")
    val id: String,
    @SerialName("summary")
    val summary: String,
    @SerialName("createdAt")
    val createdAt: Long,
    @SerialName("autoGenerated")
    val autoGenerated: Boolean,
    @SerialName("generationStatus")
    val generationStatus: String
)
