package ru.shrprnbw.ideas.data.remote.dto.response

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class TranscriptionDto(
    @SerialName("id")
    val id: String,
    @SerialName("transcription")
    val transcription: List<TranscriptionSegmentDto> = emptyList(),
    @SerialName("createdAt")
    val createdAt: Long,
    @SerialName("autoGenerated")
    val autoGenerated: Boolean,
    @SerialName("generationStatus")
    val generationStatus: String
)
